### ISSUE TITLE
show dotscience panel always

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/jupyterlab-tensorflow#12]
asked on jupyterlab gitter:

hi folks, is there a way to set which sidebar item is selected by default when JupyterLab starts up?

Ian Rose @ian-r-rose 16:41
@lukemarsden There is no trivial way, but you could do it with a custom workspace.

lukemarsden @lukemarsden 16:49
@ian-r-rose thanks! Is that something I could set up in the configuration in advance of jupyter being launched? We are distributing a JupyterLab container with a custom extension in it that we would like to always show when the user first loads JupyterLab. If you could share more info on how to do this with a custom workspace would be much appreciated :)

Ian Rose @ian-r-rose 16:50
You can launch jupyterlab with a custom layout (including which sidebar is active) using something similar to what is documented here: https://github.com/ian-r-rose/binder-workspace-demo

lukemarsden @lukemarsden 16:50
ah, awesome! Thanks!

Ian Rose @ian-r-rose 16:50
However, if you are also distributing a custom extension, it may be a better choice to activate the panel you want in the extension activate function
something like app.restored.then(() => app.shell.activateById('the-sidepanel-id'))
Either of the two approaches would work, depending on which is closer to your needs

lukemarsden @lukemarsden 16:54
ah, great! the latter sounds cleaner.
I’ll have a play. Thanks!

**Comment by alaric-dotmesh** [comment]
Hello! Please can you tell us what this is good for (eg, the whole "As a FOO i wanna X because Y" thing so we can assess the priorities?

**Comment by lukemarsden** [comment]
let's show the dotscience panel on the right hand side as well

**Comment by itamarst** [comment]
Implemented in PR linked above, will then need follow-up PR to update to new NPM package when it's released.

**Comment by itamarst** [comment]
Renovate PR should happen once npm.com's CDN expires and renovate notices new release 0.2.22 of jupyterlab-dotscience NPM pacakge.

**Comment by itamarst** [comment]
Or maybe renovate doesn't do NPM packages?
