### ISSUE TITLE
[0.5d] Update Tensorflow on dotscience docker image

### ISSUE THREAD

**Issue by satsumas** [dotmesh-io/jupyterlab-tensorflow#2]
I am hitting errors when trying to run tensorflow models on dotscience. Models that build locally don't work on my dotscience runner because the versions of tensorflow are different. Dotscience's version (1.5.1) is now quite out of date -- the more recent version is 1.11.

Could we periodically update the image we have on quay.io with important packages?  In the long run I can imagine that users would like more fine-grained control over which versions they're running, but minimally we should make sure that they're on the latest stable versions.

**Comment by satsumas** [comment]
Please could you also update keras 🙏

**Comment by lukemarsden** [comment]
This might be done but needs testing

**Comment by Godley** [comment]
Looking at the dockerfiles for tensorflow seems they use whatever's latest so this should be on latest tensorflow now
